# Generated by Django 4.2.23 on 2025-12-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='execution_time',
            field=models.FloatField(default=0.0, help_text='Execution time in seconds'),
        ),
    ]
