# Generated by Django 4.2.23 on 2025-12-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission_execution_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='anti_cheat_enabled',
            field=models.BooleanField(default=False, help_text='Enable tab-switching detection'),
        ),
    ]
