# Generated by Django 4.2.23 on 2025-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_room_anti_cheat_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='tab_switches',
            field=models.IntegerField(default=0),
        ),
    ]
